server:
    port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: spring-boot-kyb-2024-sample
  datasource:
    url: jdbc:postgresql://127.0.0.1:35432/kybexam?serverTimezone=UTC&characterEncoding=UTF-8&tinyInt1isBit=false
    username: myuser
    password: mypassword
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: username
#    password:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # 변수명 그대로 사용
      ddl-auto: create
    properties:
      jdbc:
        time-zone: Asia/Seoul
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true  # queryDSL 사용시 jpql 로 변환된 내용을 콘솔에 출력한다.
        temp:
          allow_jdbc_metadata_access: false
        default_batch_fetch_size: 50
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

# 기본접속 localhost:8080/graphiql
  graphql:
    websocket:
      path: /graphql
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true   # 수항한 쿼리를 콘솔에 출력
      locations: classpath:graphql/**/
      file-extensions: .graphqls, .gqls

logging:
  level:
    org:
      springframework:
        graphql: DEBUG
      jdbc:
        datasource:
          init: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
